"""Identidad del producto — aplicación de escritorio Wamb Groups."""

APP_NAME = "SATEC"
APP_TITLE = "Sistema de Reporte de Asistencia y Control"
APP_VERSION = "2.9.10"
AUTHOR = "Wamb Groups"
ORGANIZATION = "Wamb Groups"
WINDOW_TITLE = f"{APP_NAME} — {APP_TITLE}  |  {AUTHOR}"
APP_ID = "WambGroups.SATEC.Desktop"
GITHUB_OWNER = "wamboo5610"
GITHUB_REPO = "SATEC"
GITHUB_BRANCH = "main"
GITHUB_URL = f"https://github.com/{GITHUB_OWNER}/{GITHUB_REPO}"
