"""Identidad del producto — aplicación de escritorio WAMBOO TIC."""

APP_NAME = "SATEC"
APP_TITLE = "Sistema de Asistencia Técnico"
APP_VERSION = "2.4.0"
AUTHOR = "WAMBOO TIC"
ORGANIZATION = "WAMBOO TIC"
WINDOW_TITLE = f"{APP_NAME} — {APP_TITLE}  |  {AUTHOR}"
APP_ID = "WAMBOOTIC.SATEC.Desktop"
GITHUB_OWNER = "wamboo5610"
GITHUB_REPO = "SATEC"
GITHUB_BRANCH = "main"
GITHUB_URL = f"https://github.com/{GITHUB_OWNER}/{GITHUB_REPO}"
